---
title: "example joins"
author: "robin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{joins}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Here are some hardcoded joins to retrieve some of the information from the tables



## Soiltype

```{r}
join = "tbl_frane.Geologia.litologia" = c("diz_frane.diz_litologie.litologia",
                                          "diz_frane.diz_litologie.nome_litologia")
```



## Landuse

```{r}
join = "tbl_frane.Uso_Suolo.uso_suolo" = c("diz_frane.diz_usi_suolo.uso_suolo",
                                           "diz_frane.diz_usi_suolo.nome_uso_suolo")
```


## Type of movement

### nome_movimento

```{r}
join = "tbl_frane.clas_ii_liv.movimento" = c("diz_frane.diz_movimenti.movimento",
                                             "diz_frane.diz_movimenti.nome_movimento")
```


### tipologia

```{r}
join = "tbl_frane.Generalita.Cod_tipo" = c("diz_frane.diz_tipo_movi.cod_tipo",
                                             "diz_frane.diz_tipo_movi.tipologia")
```


## Material

```{r}
join = "tbl_frane.clas_ii_liv.materiale" = c("diz_frane.diz_materiali.materiale",
                                             "diz_frane.diz_materiali.nome_materiale")
```


## Watercontent

```{r}
join = "tbl_frane.clas_ii_liv.acqua" = c("diz_frane.diz_acqua.acqua",
                                             "diz_frane.diz_acqua.nome_acqua")
```


## Velocity

```{r}
join = "tbl_frane.clas_ii_liv.velocita" = c("diz_frane.diz_velocita.velocita",
                                             "diz_frane.diz_velocita.nome_velocita")
```


## Cause

```{r}
join = "tbl_frane.ass_gen_cause.causa" = c("diz_frane.diz_cause.causa",
                                      "diz_frane.diz_cause.nome_causa")
```



## style


```{r}
join = "tbl_frane.Attivita.stile" = c("diz_frane.diz_stile.stile",
                                      "diz_frane.diz_stile.nome_stile")
```

